docker_tls:
        ca_path: "/root/.docker/ca.pem"
        client_cert: ["/root/.docker/cert.pem", "/root/.docker/key.pem"]

docker:
        connection: "tcp://172.16.1.3" 
        port:  2375
host:
        ebot_ip: "172.16.1.3"
        csgo_servers_ip:
                - "172.16.1.3"
                - "172.16.1.4"
                - "172.16.1.5"
csgo:
        tokens:
                - "string"
        image_name: "csgoserver"
        nb_instances: 4
