docker_tls:
        ca_cert: "/root/.docker/ca.pem"
        client_cert: ["/root/.docker/cert.pem", "/root/.docker/key.pem"]

host:
        ebot_ip: "127.0.0.1"
        csgo_servers_ip:
                - "127.0.0.1"

csgo:
        tokens:
                - "string"
                - "string2"
        image_name: "csgoserver"
        nb_instances: 2
