FROM ubuntu:15.10
MAINTAINER nominoe kervadec <nominoe.kervadec@insa-rennes.fr>

# install required dependencies
RUN dpkg --add-architecture i386
RUN apt-get update
RUN apt-get install -y wget lib32gcc1 libstdc++6 unzip


# install steamcmd
RUN useradd -ms /bin/bash steam
WORKDIR /home/steam
USER steam
RUN wget -O /tmp/steamcmd_linux.tar.gz http://media.steampowered.com/installer/steamcmd_linux.tar.gz
RUN tar -xvzf /tmp/steamcmd_linux.tar.gz
RUN rm /tmp/steamcmd_linux.tar.gz

# install steamcmd and csgo up to date
RUN ./steamcmd.sh +login anonymous +force_install_dir csgo/ +app_update 740 validate +quit

ENV CSGO_HOSTNAME insalan csgo test
ENV CSGO_PASSWORD ""
ENV RCON_PASSWORD banana
ENV STEAM_ACCOUNT_TOKEN ""

EXPOSE 27015/udp
EXPOSE 27015

ADD ./entrypoint.sh entrypoint.sh

# add default configuration files
ADD cfg/ /home/steam/csgo/csgo/cfg

CMD ./entrypoint.sh
